# Generated by Django 2.0 on 2020-01-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heading',
            new_name='SportData',
        ),
    ]
