# Generated by Django 2.0 on 2020-01-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200104_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Select',
        ),
    ]
