# Generated by Django 2.0 on 2020-01-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_delete_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
            ],
        ),
    ]
